# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tino/streaming/v1/streaming.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tino/streaming/v1/streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!tino/streaming/v1/streaming.proto\x12\x11tino.streaming.v1\"i\n\x10SubscribeRequest\x12\x1e\n\ninstrument\x18\x01 \x01(\tR\ninstrument\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\x12\x1d\n\nevent_type\x18\x03 \x01(\tR\teventType\"\xe1\x02\n\x11SubscribeResponse\x12\x42\n\x04type\x18\x01 \x01(\x0e\x32..tino.streaming.v1.SubscribeResponse.EventTypeR\x04type\x12\x1e\n\ninstrument\x18\x02 \x01(\tR\ninstrument\x12\x1b\n\tdata_json\x18\x03 \x01(\tR\x08\x64\x61taJson\x12\x1c\n\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x16\n\x06source\x18\x05 \x01(\tR\x06source\"\x94\x01\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x45VENT_TYPE_QUOTE\x10\x01\x12\x14\n\x10\x45VENT_TYPE_TRADE\x10\x02\x12\x12\n\x0e\x45VENT_TYPE_BAR\x10\x03\x12\x15\n\x11\x45VENT_TYPE_STATUS\x10\x04\x12\x14\n\x10\x45VENT_TYPE_ERROR\x10\x05\"L\n\x12UnsubscribeRequest\x12\x1e\n\ninstrument\x18\x01 \x01(\tR\ninstrument\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\"/\n\x13UnsubscribeResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"\x1a\n\x18ListSubscriptionsRequest\"b\n\x19ListSubscriptionsResponse\x12\x45\n\rsubscriptions\x18\x01 \x03(\x0b\x32\x1f.tino.streaming.v1.SubscriptionR\rsubscriptions\"e\n\x0cSubscription\x12\x1e\n\ninstrument\x18\x01 \x01(\tR\ninstrument\x12\x16\n\x06source\x18\x02 \x01(\tR\x06source\x12\x1d\n\nevent_type\x18\x03 \x01(\tR\teventType2\xba\x02\n\x10StreamingService\x12X\n\tSubscribe\x12#.tino.streaming.v1.SubscribeRequest\x1a$.tino.streaming.v1.SubscribeResponse0\x01\x12\\\n\x0bUnsubscribe\x12%.tino.streaming.v1.UnsubscribeRequest\x1a&.tino.streaming.v1.UnsubscribeResponse\x12n\n\x11ListSubscriptions\x12+.tino.streaming.v1.ListSubscriptionsRequest\x1a,.tino.streaming.v1.ListSubscriptionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tino.streaming.v1.streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=56
  _globals['_SUBSCRIBEREQUEST']._serialized_end=161
  _globals['_SUBSCRIBERESPONSE']._serialized_start=164
  _globals['_SUBSCRIBERESPONSE']._serialized_end=517
  _globals['_SUBSCRIBERESPONSE_EVENTTYPE']._serialized_start=369
  _globals['_SUBSCRIBERESPONSE_EVENTTYPE']._serialized_end=517
  _globals['_UNSUBSCRIBEREQUEST']._serialized_start=519
  _globals['_UNSUBSCRIBEREQUEST']._serialized_end=595
  _globals['_UNSUBSCRIBERESPONSE']._serialized_start=597
  _globals['_UNSUBSCRIBERESPONSE']._serialized_end=644
  _globals['_LISTSUBSCRIPTIONSREQUEST']._serialized_start=646
  _globals['_LISTSUBSCRIPTIONSREQUEST']._serialized_end=672
  _globals['_LISTSUBSCRIPTIONSRESPONSE']._serialized_start=674
  _globals['_LISTSUBSCRIPTIONSRESPONSE']._serialized_end=772
  _globals['_SUBSCRIPTION']._serialized_start=774
  _globals['_SUBSCRIPTION']._serialized_end=875
  _globals['_STREAMINGSERVICE']._serialized_start=878
  _globals['_STREAMINGSERVICE']._serialized_end=1192
# @@protoc_insertion_point(module_scope)
