# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.streaming.v1 import streaming_pb2 as tino_dot_streaming_dot_v1_dot_streaming__pb2


class StreamingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/tino.streaming.v1.StreamingService/Subscribe',
                request_serializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/tino.streaming.v1.StreamingService/Unsubscribe',
                request_serializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)
        self.ListSubscriptions = channel.unary_unary(
                '/tino.streaming.v1.StreamingService/ListSubscriptions',
                request_serializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.ListSubscriptionsRequest.SerializeToString,
                response_deserializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.ListSubscriptionsResponse.FromString,
                _registered_method=True)


class StreamingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubscriptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.SubscribeRequest.FromString,
                    response_serializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.SubscribeResponse.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.UnsubscribeRequest.FromString,
                    response_serializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'ListSubscriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubscriptions,
                    request_deserializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.ListSubscriptionsRequest.FromString,
                    response_serializer=tino_dot_streaming_dot_v1_dot_streaming__pb2.ListSubscriptionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.streaming.v1.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.streaming.v1.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tino.streaming.v1.StreamingService/Subscribe',
            tino_dot_streaming_dot_v1_dot_streaming__pb2.SubscribeRequest.SerializeToString,
            tino_dot_streaming_dot_v1_dot_streaming__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.streaming.v1.StreamingService/Unsubscribe',
            tino_dot_streaming_dot_v1_dot_streaming__pb2.UnsubscribeRequest.SerializeToString,
            tino_dot_streaming_dot_v1_dot_streaming__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.streaming.v1.StreamingService/ListSubscriptions',
            tino_dot_streaming_dot_v1_dot_streaming__pb2.ListSubscriptionsRequest.SerializeToString,
            tino_dot_streaming_dot_v1_dot_streaming__pb2.ListSubscriptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
