# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.trading.v1 import trading_pb2 as tino_dot_trading_dot_v1_dot_trading__pb2


class TradingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTrading = channel.unary_stream(
                '/tino.trading.v1.TradingService/StartTrading',
                request_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.StartTradingRequest.SerializeToString,
                response_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.StartTradingResponse.FromString,
                _registered_method=True)
        self.StopTrading = channel.unary_unary(
                '/tino.trading.v1.TradingService/StopTrading',
                request_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.StopTradingRequest.SerializeToString,
                response_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.StopTradingResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/tino.trading.v1.TradingService/GetPositions',
                request_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetPositionsRequest.SerializeToString,
                response_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetPositionsResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/tino.trading.v1.TradingService/GetOrders',
                request_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetOrdersResponse.FromString,
                _registered_method=True)
        self.SubmitOrder = channel.unary_unary(
                '/tino.trading.v1.TradingService/SubmitOrder',
                request_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.SubmitOrderRequest.SerializeToString,
                response_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.SubmitOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/tino.trading.v1.TradingService/CancelOrder',
                request_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.GetAccountSummary = channel.unary_unary(
                '/tino.trading.v1.TradingService/GetAccountSummary',
                request_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetAccountSummaryRequest.SerializeToString,
                response_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetAccountSummaryResponse.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTrading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTrading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTrading': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTrading,
                    request_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.StartTradingRequest.FromString,
                    response_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.StartTradingResponse.SerializeToString,
            ),
            'StopTrading': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTrading,
                    request_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.StopTradingRequest.FromString,
                    response_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.StopTradingResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetPositionsRequest.FromString,
                    response_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetPositionsResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetOrdersRequest.FromString,
                    response_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetOrdersResponse.SerializeToString,
            ),
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.SubmitOrderRequest.FromString,
                    response_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.SubmitOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.CancelOrderRequest.FromString,
                    response_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetAccountSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountSummary,
                    request_deserializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetAccountSummaryRequest.FromString,
                    response_serializer=tino_dot_trading_dot_v1_dot_trading__pb2.GetAccountSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.trading.v1.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.trading.v1.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTrading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tino.trading.v1.TradingService/StartTrading',
            tino_dot_trading_dot_v1_dot_trading__pb2.StartTradingRequest.SerializeToString,
            tino_dot_trading_dot_v1_dot_trading__pb2.StartTradingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTrading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.trading.v1.TradingService/StopTrading',
            tino_dot_trading_dot_v1_dot_trading__pb2.StopTradingRequest.SerializeToString,
            tino_dot_trading_dot_v1_dot_trading__pb2.StopTradingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.trading.v1.TradingService/GetPositions',
            tino_dot_trading_dot_v1_dot_trading__pb2.GetPositionsRequest.SerializeToString,
            tino_dot_trading_dot_v1_dot_trading__pb2.GetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.trading.v1.TradingService/GetOrders',
            tino_dot_trading_dot_v1_dot_trading__pb2.GetOrdersRequest.SerializeToString,
            tino_dot_trading_dot_v1_dot_trading__pb2.GetOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.trading.v1.TradingService/SubmitOrder',
            tino_dot_trading_dot_v1_dot_trading__pb2.SubmitOrderRequest.SerializeToString,
            tino_dot_trading_dot_v1_dot_trading__pb2.SubmitOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.trading.v1.TradingService/CancelOrder',
            tino_dot_trading_dot_v1_dot_trading__pb2.CancelOrderRequest.SerializeToString,
            tino_dot_trading_dot_v1_dot_trading__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.trading.v1.TradingService/GetAccountSummary',
            tino_dot_trading_dot_v1_dot_trading__pb2.GetAccountSummaryRequest.SerializeToString,
            tino_dot_trading_dot_v1_dot_trading__pb2.GetAccountSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
