# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.daemon.v1 import daemon_pb2 as tino_dot_daemon_dot_v1_dot_daemon__pb2


class DaemonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemInfo = channel.unary_unary(
                '/tino.daemon.v1.DaemonService/GetSystemInfo',
                request_serializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.GetSystemInfoRequest.SerializeToString,
                response_deserializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.GetSystemInfoResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/tino.daemon.v1.DaemonService/Shutdown',
                request_serializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/tino.daemon.v1.DaemonService/HealthCheck',
                request_serializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class DaemonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInfo,
                    request_deserializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.GetSystemInfoRequest.FromString,
                    response_serializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.GetSystemInfoResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.ShutdownRequest.FromString,
                    response_serializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.ShutdownResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.HealthCheckRequest.FromString,
                    response_serializer=tino_dot_daemon_dot_v1_dot_daemon__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.daemon.v1.DaemonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.daemon.v1.DaemonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaemonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.daemon.v1.DaemonService/GetSystemInfo',
            tino_dot_daemon_dot_v1_dot_daemon__pb2.GetSystemInfoRequest.SerializeToString,
            tino_dot_daemon_dot_v1_dot_daemon__pb2.GetSystemInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.daemon.v1.DaemonService/Shutdown',
            tino_dot_daemon_dot_v1_dot_daemon__pb2.ShutdownRequest.SerializeToString,
            tino_dot_daemon_dot_v1_dot_daemon__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.daemon.v1.DaemonService/HealthCheck',
            tino_dot_daemon_dot_v1_dot_daemon__pb2.HealthCheckRequest.SerializeToString,
            tino_dot_daemon_dot_v1_dot_daemon__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
