# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tino/daemon/v1/daemon.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tino/daemon/v1/daemon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btino/daemon/v1/daemon.proto\x12\x0etino.daemon.v1\"\x16\n\x14GetSystemInfoRequest\"\xaf\x01\n\x15GetSystemInfoResponse\x12%\n\x0epython_version\x18\x01 \x01(\tR\rpythonVersion\x12)\n\x10nautilus_version\x18\x02 \x01(\tR\x0fnautilusVersion\x12,\n\x12memory_usage_bytes\x18\x03 \x01(\x04R\x10memoryUsageBytes\x12\x16\n\x06uptime\x18\x04 \x01(\tR\x06uptime\"\x11\n\x0fShutdownRequest\",\n\x10ShutdownResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success2\xbc\x01\n\rDaemonService\x12\\\n\rGetSystemInfo\x12$.tino.daemon.v1.GetSystemInfoRequest\x1a%.tino.daemon.v1.GetSystemInfoResponse\x12M\n\x08Shutdown\x12\x1f.tino.daemon.v1.ShutdownRequest\x1a .tino.daemon.v1.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tino.daemon.v1.daemon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSYSTEMINFOREQUEST']._serialized_start=47
  _globals['_GETSYSTEMINFOREQUEST']._serialized_end=69
  _globals['_GETSYSTEMINFORESPONSE']._serialized_start=72
  _globals['_GETSYSTEMINFORESPONSE']._serialized_end=247
  _globals['_SHUTDOWNREQUEST']._serialized_start=249
  _globals['_SHUTDOWNREQUEST']._serialized_end=266
  _globals['_SHUTDOWNRESPONSE']._serialized_start=268
  _globals['_SHUTDOWNRESPONSE']._serialized_end=312
  _globals['_DAEMONSERVICE']._serialized_start=315
  _globals['_DAEMONSERVICE']._serialized_end=503
# @@protoc_insertion_point(module_scope)
