"""Pydantic schemas for the trading engine."""

from .strategy import (
    StrategyCreate,
    StrategyResponse,
    StrategyListItem,
    StrategyListResponse,
    StrategyCreateResponse,
)
from .backtest import (
    BacktestStatus,
    BacktestMetrics,
    TradeLogEntry,
    EquityCurvePoint,
    BacktestCreate,
    BacktestRun,
    BacktestCreateResponse,
)
from .live_session import (
    LifecycleState,
    Position,
    Order,
    PauseResumeEntry,
    LiveDeploy,
    LiveSession,
    LiveDeployResponse,
    KillSwitchResponse,
)
from .risk import (
    RiskModificationLogEntry,
    RiskProfile,
    RiskProfileUpdate,
)
from .events import (
    EventEnvelope,
    BacktestProgressEvent,
    BacktestCompletedEvent,
    BacktestFailedEvent,
    BacktestCancelEvent,
    LiveStateChangeEvent,
    LivePositionUpdateEvent,
    LiveOrderEvent,
    LiveTradeExecutedEvent,
    LiveRiskAlertEvent,
    LiveRiskCircuitBreakerEvent,
    LiveErrorEvent,
    DashboardSessionListEvent,
    PingEvent,
    PongEvent,
)

__all__ = [
    "StrategyCreate",
    "StrategyResponse",
    "StrategyListItem",
    "StrategyListResponse",
    "StrategyCreateResponse",
    "BacktestStatus",
    "BacktestMetrics",
    "TradeLogEntry",
    "EquityCurvePoint",
    "BacktestCreate",
    "BacktestRun",
    "BacktestCreateResponse",
    "LifecycleState",
    "Position",
    "Order",
    "PauseResumeEntry",
    "LiveDeploy",
    "LiveSession",
    "LiveDeployResponse",
    "KillSwitchResponse",
    "RiskModificationLogEntry",
    "RiskProfile",
    "RiskProfileUpdate",
    "EventEnvelope",
    "BacktestProgressEvent",
    "BacktestCompletedEvent",
    "BacktestFailedEvent",
    "BacktestCancelEvent",
    "LiveStateChangeEvent",
    "LivePositionUpdateEvent",
    "LiveOrderEvent",
    "LiveTradeExecutedEvent",
    "LiveRiskAlertEvent",
    "LiveRiskCircuitBreakerEvent",
    "LiveErrorEvent",
    "DashboardSessionListEvent",
    "PingEvent",
    "PongEvent",
]
