# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.portfolio.v1 import portfolio_pb2 as tino_dot_portfolio_dot_v1_dot_portfolio__pb2


class PortfolioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordTrade = channel.unary_unary(
                '/tino.portfolio.v1.PortfolioService/RecordTrade',
                request_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.RecordTradeRequest.SerializeToString,
                response_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.RecordTradeResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/tino.portfolio.v1.PortfolioService/GetPositions',
                request_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPositionsRequest.SerializeToString,
                response_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPositionsResponse.FromString,
                _registered_method=True)
        self.GetTrades = channel.unary_unary(
                '/tino.portfolio.v1.PortfolioService/GetTrades',
                request_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetTradesRequest.SerializeToString,
                response_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetTradesResponse.FromString,
                _registered_method=True)
        self.GetPnLHistory = channel.unary_unary(
                '/tino.portfolio.v1.PortfolioService/GetPnLHistory',
                request_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPnLHistoryRequest.SerializeToString,
                response_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPnLHistoryResponse.FromString,
                _registered_method=True)
        self.GetSummary = channel.unary_unary(
                '/tino.portfolio.v1.PortfolioService/GetSummary',
                request_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetSummaryRequest.SerializeToString,
                response_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetSummaryResponse.FromString,
                _registered_method=True)


class PortfolioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPnLHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTrade,
                    request_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.RecordTradeRequest.FromString,
                    response_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.RecordTradeResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPositionsRequest.FromString,
                    response_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPositionsResponse.SerializeToString,
            ),
            'GetTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrades,
                    request_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetTradesRequest.FromString,
                    response_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetTradesResponse.SerializeToString,
            ),
            'GetPnLHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPnLHistory,
                    request_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPnLHistoryRequest.FromString,
                    response_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPnLHistoryResponse.SerializeToString,
            ),
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetSummaryRequest.FromString,
                    response_serializer=tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.portfolio.v1.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.portfolio.v1.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.portfolio.v1.PortfolioService/RecordTrade',
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.RecordTradeRequest.SerializeToString,
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.RecordTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.portfolio.v1.PortfolioService/GetPositions',
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPositionsRequest.SerializeToString,
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.portfolio.v1.PortfolioService/GetTrades',
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetTradesRequest.SerializeToString,
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPnLHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.portfolio.v1.PortfolioService/GetPnLHistory',
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPnLHistoryRequest.SerializeToString,
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetPnLHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.portfolio.v1.PortfolioService/GetSummary',
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetSummaryRequest.SerializeToString,
            tino_dot_portfolio_dot_v1_dot_portfolio__pb2.GetSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
