# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.exchange.v1 import exchange_pb2 as tino_dot_exchange_dot_v1_dot_exchange__pb2


class ExchangeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTicker = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/GetTicker',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetTickerRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetTickerResponse.FromString,
                _registered_method=True)
        self.GetKlines = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/GetKlines',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetKlinesRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetKlinesResponse.FromString,
                _registered_method=True)
        self.GetFundingRate = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/GetFundingRate',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetFundingRateRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetFundingRateResponse.FromString,
                _registered_method=True)
        self.GetOrderbook = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/GetOrderbook',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetOrderbookRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetOrderbookResponse.FromString,
                _registered_method=True)
        self.GetAccountBalance = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/GetAccountBalance',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetAccountBalanceRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetAccountBalanceResponse.FromString,
                _registered_method=True)
        self.GetExchangePositions = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/GetExchangePositions',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetExchangePositionsRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetExchangePositionsResponse.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/PlaceOrder',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.CancelExchangeOrder = channel.unary_unary(
                '/tino.exchange.v1.ExchangeService/CancelExchangeOrder',
                request_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.CancelExchangeOrderRequest.SerializeToString,
                response_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.CancelExchangeOrderResponse.FromString,
                _registered_method=True)


class ExchangeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTicker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKlines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFundingRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderbook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExchangePositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelExchangeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTicker': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicker,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetTickerRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetTickerResponse.SerializeToString,
            ),
            'GetKlines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKlines,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetKlinesRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetKlinesResponse.SerializeToString,
            ),
            'GetFundingRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFundingRate,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetFundingRateRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetFundingRateResponse.SerializeToString,
            ),
            'GetOrderbook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderbook,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetOrderbookRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetOrderbookResponse.SerializeToString,
            ),
            'GetAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalance,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetAccountBalanceRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetAccountBalanceResponse.SerializeToString,
            ),
            'GetExchangePositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchangePositions,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetExchangePositionsRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.GetExchangePositionsResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.PlaceOrderRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CancelExchangeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelExchangeOrder,
                    request_deserializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.CancelExchangeOrderRequest.FromString,
                    response_serializer=tino_dot_exchange_dot_v1_dot_exchange__pb2.CancelExchangeOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.exchange.v1.ExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.exchange.v1.ExchangeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExchangeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTicker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/GetTicker',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetTickerRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetTickerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/GetKlines',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetKlinesRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetKlinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFundingRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/GetFundingRate',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetFundingRateRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetFundingRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderbook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/GetOrderbook',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetOrderbookRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetOrderbookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/GetAccountBalance',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetAccountBalanceRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetAccountBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExchangePositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/GetExchangePositions',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetExchangePositionsRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.GetExchangePositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/PlaceOrder',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.PlaceOrderRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelExchangeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.exchange.v1.ExchangeService/CancelExchangeOrder',
            tino_dot_exchange_dot_v1_dot_exchange__pb2.CancelExchangeOrderRequest.SerializeToString,
            tino_dot_exchange_dot_v1_dot_exchange__pb2.CancelExchangeOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
