name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type/bug", "status/triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior.
      placeholder: |
        1. Run `tino ...`
        2. Enter query '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the impact?
      options:
        - Critical (crash/data loss)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor inconvenience)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which component(s) are affected?
      multiple: true
      options:
        - CLI / TUI
        - Python Daemon
        - gRPC / ConnectRPC
        - Agent Tools
        - Trading (Live/Paper)
        - Data Providers
        - Configuration
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Tino are you using?
      placeholder: "e.g., 0.1.0 or commit hash"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Paste any relevant log output or error messages.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Bun version, Python version, etc.
      placeholder: |
        - OS: macOS 15.x
        - Bun: 1.x.x
        - Python: 3.12.x

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I can reproduce this on the latest version
