# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tino/chart/v1/chart.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tino/chart/v1/chart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19tino/chart/v1/chart.proto\x12\rtino.chart.v1\"\xc4\x01\n\x18RenderCandlestickRequest\x12\x14\n\x05\x64\x61tes\x18\x01 \x03(\tR\x05\x64\x61tes\x12\x12\n\x04open\x18\x02 \x03(\x01R\x04open\x12\x14\n\x05\x63lose\x18\x03 \x03(\x01R\x05\x63lose\x12\x12\n\x04high\x18\x04 \x03(\x01R\x04high\x12\x10\n\x03low\x18\x05 \x03(\x01R\x03low\x12\x14\n\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x07 \x01(\x05R\x06height\x12\x14\n\x05title\x18\x08 \x01(\tR\x05title\":\n\x19RenderCandlestickResponse\x12\x1d\n\nansi_chart\x18\x01 \x01(\tR\tansiChart\"\xa2\x01\n\x16RenderLineChartRequest\x12\x16\n\x06labels\x18\x01 \x03(\tR\x06labels\x12\x16\n\x06values\x18\x02 \x03(\x01R\x06values\x12\x14\n\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x04 \x01(\x05R\x06height\x12\x14\n\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n\x05\x63olor\x18\x06 \x01(\tR\x05\x63olor\"8\n\x17RenderLineChartResponse\x12\x1d\n\nansi_chart\x18\x01 \x01(\tR\tansiChart\"\xc2\x01\n\x14RenderSubplotRequest\x12\x14\n\x05\x64\x61tes\x18\x01 \x03(\tR\x05\x64\x61tes\x12\x12\n\x04open\x18\x02 \x03(\x01R\x04open\x12\x14\n\x05\x63lose\x18\x03 \x03(\x01R\x05\x63lose\x12\x12\n\x04high\x18\x04 \x03(\x01R\x04high\x12\x10\n\x03low\x18\x05 \x03(\x01R\x03low\x12\x16\n\x06volume\x18\x06 \x03(\x01R\x06volume\x12\x14\n\x05width\x18\x07 \x01(\x05R\x05width\x12\x16\n\x06height\x18\x08 \x01(\x05R\x06height\"6\n\x15RenderSubplotResponse\x12\x1d\n\nansi_chart\x18\x01 \x01(\tR\tansiChart2\xb4\x02\n\x0c\x43hartService\x12\x66\n\x11RenderCandlestick\x12\'.tino.chart.v1.RenderCandlestickRequest\x1a(.tino.chart.v1.RenderCandlestickResponse\x12`\n\x0fRenderLineChart\x12%.tino.chart.v1.RenderLineChartRequest\x1a&.tino.chart.v1.RenderLineChartResponse\x12Z\n\rRenderSubplot\x12#.tino.chart.v1.RenderSubplotRequest\x1a$.tino.chart.v1.RenderSubplotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tino.chart.v1.chart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENDERCANDLESTICKREQUEST']._serialized_start=45
  _globals['_RENDERCANDLESTICKREQUEST']._serialized_end=241
  _globals['_RENDERCANDLESTICKRESPONSE']._serialized_start=243
  _globals['_RENDERCANDLESTICKRESPONSE']._serialized_end=301
  _globals['_RENDERLINECHARTREQUEST']._serialized_start=304
  _globals['_RENDERLINECHARTREQUEST']._serialized_end=466
  _globals['_RENDERLINECHARTRESPONSE']._serialized_start=468
  _globals['_RENDERLINECHARTRESPONSE']._serialized_end=524
  _globals['_RENDERSUBPLOTREQUEST']._serialized_start=527
  _globals['_RENDERSUBPLOTREQUEST']._serialized_end=721
  _globals['_RENDERSUBPLOTRESPONSE']._serialized_start=723
  _globals['_RENDERSUBPLOTRESPONSE']._serialized_end=777
  _globals['_CHARTSERVICE']._serialized_start=780
  _globals['_CHARTSERVICE']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
