# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.chart.v1 import chart_pb2 as tino_dot_chart_dot_v1_dot_chart__pb2


class ChartServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenderCandlestick = channel.unary_unary(
                '/tino.chart.v1.ChartService/RenderCandlestick',
                request_serializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderCandlestickRequest.SerializeToString,
                response_deserializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderCandlestickResponse.FromString,
                _registered_method=True)
        self.RenderLineChart = channel.unary_unary(
                '/tino.chart.v1.ChartService/RenderLineChart',
                request_serializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderLineChartRequest.SerializeToString,
                response_deserializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderLineChartResponse.FromString,
                _registered_method=True)
        self.RenderSubplot = channel.unary_unary(
                '/tino.chart.v1.ChartService/RenderSubplot',
                request_serializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderSubplotRequest.SerializeToString,
                response_deserializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderSubplotResponse.FromString,
                _registered_method=True)


class ChartServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RenderCandlestick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderLineChart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderSubplot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenderCandlestick': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderCandlestick,
                    request_deserializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderCandlestickRequest.FromString,
                    response_serializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderCandlestickResponse.SerializeToString,
            ),
            'RenderLineChart': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderLineChart,
                    request_deserializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderLineChartRequest.FromString,
                    response_serializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderLineChartResponse.SerializeToString,
            ),
            'RenderSubplot': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderSubplot,
                    request_deserializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderSubplotRequest.FromString,
                    response_serializer=tino_dot_chart_dot_v1_dot_chart__pb2.RenderSubplotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.chart.v1.ChartService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.chart.v1.ChartService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChartService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RenderCandlestick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.chart.v1.ChartService/RenderCandlestick',
            tino_dot_chart_dot_v1_dot_chart__pb2.RenderCandlestickRequest.SerializeToString,
            tino_dot_chart_dot_v1_dot_chart__pb2.RenderCandlestickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderLineChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.chart.v1.ChartService/RenderLineChart',
            tino_dot_chart_dot_v1_dot_chart__pb2.RenderLineChartRequest.SerializeToString,
            tino_dot_chart_dot_v1_dot_chart__pb2.RenderLineChartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderSubplot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.chart.v1.ChartService/RenderSubplot',
            tino_dot_chart_dot_v1_dot_chart__pb2.RenderSubplotRequest.SerializeToString,
            tino_dot_chart_dot_v1_dot_chart__pb2.RenderSubplotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
