# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.backtest.v1 import backtest_pb2 as tino_dot_backtest_dot_v1_dot_backtest__pb2


class BacktestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunBacktest = channel.unary_stream(
                '/tino.backtest.v1.BacktestService/RunBacktest',
                request_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.RunBacktestRequest.SerializeToString,
                response_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.RunBacktestResponse.FromString,
                _registered_method=True)
        self.CancelBacktest = channel.unary_unary(
                '/tino.backtest.v1.BacktestService/CancelBacktest',
                request_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.CancelBacktestRequest.SerializeToString,
                response_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.CancelBacktestResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/tino.backtest.v1.BacktestService/GetResult',
                request_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.GetResultRequest.SerializeToString,
                response_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.GetResultResponse.FromString,
                _registered_method=True)
        self.ListResults = channel.unary_unary(
                '/tino.backtest.v1.BacktestService/ListResults',
                request_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.ListResultsRequest.SerializeToString,
                response_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.ListResultsResponse.FromString,
                _registered_method=True)


class BacktestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunBacktest': grpc.unary_stream_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.RunBacktestRequest.FromString,
                    response_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.RunBacktestResponse.SerializeToString,
            ),
            'CancelBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBacktest,
                    request_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.CancelBacktestRequest.FromString,
                    response_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.CancelBacktestResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.GetResultRequest.FromString,
                    response_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.GetResultResponse.SerializeToString,
            ),
            'ListResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResults,
                    request_deserializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.ListResultsRequest.FromString,
                    response_serializer=tino_dot_backtest_dot_v1_dot_backtest__pb2.ListResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.backtest.v1.BacktestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.backtest.v1.BacktestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BacktestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tino.backtest.v1.BacktestService/RunBacktest',
            tino_dot_backtest_dot_v1_dot_backtest__pb2.RunBacktestRequest.SerializeToString,
            tino_dot_backtest_dot_v1_dot_backtest__pb2.RunBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.backtest.v1.BacktestService/CancelBacktest',
            tino_dot_backtest_dot_v1_dot_backtest__pb2.CancelBacktestRequest.SerializeToString,
            tino_dot_backtest_dot_v1_dot_backtest__pb2.CancelBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.backtest.v1.BacktestService/GetResult',
            tino_dot_backtest_dot_v1_dot_backtest__pb2.GetResultRequest.SerializeToString,
            tino_dot_backtest_dot_v1_dot_backtest__pb2.GetResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.backtest.v1.BacktestService/ListResults',
            tino_dot_backtest_dot_v1_dot_backtest__pb2.ListResultsRequest.SerializeToString,
            tino_dot_backtest_dot_v1_dot_backtest__pb2.ListResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
