# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tino/backtest/v1/optimization.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tino/backtest/v1/optimization.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#tino/backtest/v1/optimization.proto\x12\x10tino.backtest.v1\"\xba\x02\n\x11GridSearchRequest\x12#\n\rstrategy_path\x18\x01 \x01(\tR\x0cstrategyPath\x12\x1e\n\ninstrument\x18\x02 \x01(\tR\ninstrument\x12\x19\n\x08\x62\x61r_type\x18\x03 \x01(\tR\x07\x62\x61rType\x12\x1d\n\nstart_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n\x08\x65nd_date\x18\x05 \x01(\tR\x07\x65ndDate\x12*\n\x11param_ranges_json\x18\x06 \x01(\tR\x0fparamRangesJson\x12)\n\x10max_combinations\x18\x07 \x01(\x05R\x0fmaxCombinations\x12\x1f\n\x0brank_metric\x18\x08 \x01(\tR\nrankMetric\x12\x13\n\x05top_n\x18\t \x01(\x05R\x04topN\"\xb0\x03\n\x12GridSearchResponse\x12\x42\n\x04type\x18\x01 \x01(\x0e\x32..tino.backtest.v1.GridSearchResponse.EventTypeR\x04type\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12!\n\x0cprogress_pct\x18\x03 \x01(\x01R\x0bprogressPct\x12-\n\x12total_combinations\x18\x04 \x01(\x05R\x11totalCombinations\x12\x35\n\x16\x63ompleted_combinations\x18\x05 \x01(\x05R\x15\x63ompletedCombinations\x12\x41\n\x07results\x18\x06 \x03(\x0b\x32\'.tino.backtest.v1.GridSearchResultEntryR\x07results\"p\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x45VENT_TYPE_PROGRESS\x10\x01\x12\x18\n\x14\x45VENT_TYPE_COMPLETED\x10\x02\x12\x14\n\x10\x45VENT_TYPE_ERROR\x10\x03\"\xdb\x01\n\x15GridSearchResultEntry\x12\x1f\n\x0bparams_json\x18\x01 \x01(\tR\nparamsJson\x12!\n\x0csharpe_ratio\x18\x02 \x01(\x01R\x0bsharpeRatio\x12!\n\x0ctotal_return\x18\x03 \x01(\x01R\x0btotalReturn\x12!\n\x0cmax_drawdown\x18\x04 \x01(\x01R\x0bmaxDrawdown\x12\x19\n\x08win_rate\x18\x05 \x01(\x01R\x07winRate\x12\x1d\n\nnum_trades\x18\x06 \x01(\x05R\tnumTrades2q\n\x11GridSearchService\x12\\\n\rRunGridSearch\x12#.tino.backtest.v1.GridSearchRequest\x1a$.tino.backtest.v1.GridSearchResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tino.backtest.v1.optimization_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRIDSEARCHREQUEST']._serialized_start=58
  _globals['_GRIDSEARCHREQUEST']._serialized_end=372
  _globals['_GRIDSEARCHRESPONSE']._serialized_start=375
  _globals['_GRIDSEARCHRESPONSE']._serialized_end=807
  _globals['_GRIDSEARCHRESPONSE_EVENTTYPE']._serialized_start=695
  _globals['_GRIDSEARCHRESPONSE_EVENTTYPE']._serialized_end=807
  _globals['_GRIDSEARCHRESULTENTRY']._serialized_start=810
  _globals['_GRIDSEARCHRESULTENTRY']._serialized_end=1029
  _globals['_GRIDSEARCHSERVICE']._serialized_start=1031
  _globals['_GRIDSEARCHSERVICE']._serialized_end=1144
# @@protoc_insertion_point(module_scope)
