# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.backtest.v1 import optimization_pb2 as tino_dot_backtest_dot_v1_dot_optimization__pb2


class GridSearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunGridSearch = channel.unary_stream(
                '/tino.backtest.v1.GridSearchService/RunGridSearch',
                request_serializer=tino_dot_backtest_dot_v1_dot_optimization__pb2.GridSearchRequest.SerializeToString,
                response_deserializer=tino_dot_backtest_dot_v1_dot_optimization__pb2.GridSearchResponse.FromString,
                _registered_method=True)


class GridSearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunGridSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GridSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunGridSearch': grpc.unary_stream_rpc_method_handler(
                    servicer.RunGridSearch,
                    request_deserializer=tino_dot_backtest_dot_v1_dot_optimization__pb2.GridSearchRequest.FromString,
                    response_serializer=tino_dot_backtest_dot_v1_dot_optimization__pb2.GridSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.backtest.v1.GridSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.backtest.v1.GridSearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GridSearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunGridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tino.backtest.v1.GridSearchService/RunGridSearch',
            tino_dot_backtest_dot_v1_dot_optimization__pb2.GridSearchRequest.SerializeToString,
            tino_dot_backtest_dot_v1_dot_optimization__pb2.GridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
