# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tino.analytics.v1 import analytics_pb2 as tino_dot_analytics_dot_v1_dot_analytics__pb2


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectAnomalies = channel.unary_unary(
                '/tino.analytics.v1.AnalyticsService/DetectAnomalies',
                request_serializer=tino_dot_analytics_dot_v1_dot_analytics__pb2.DetectAnomaliesRequest.SerializeToString,
                response_deserializer=tino_dot_analytics_dot_v1_dot_analytics__pb2.DetectAnomaliesResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomalies,
                    request_deserializer=tino_dot_analytics_dot_v1_dot_analytics__pb2.DetectAnomaliesRequest.FromString,
                    response_serializer=tino_dot_analytics_dot_v1_dot_analytics__pb2.DetectAnomaliesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tino.analytics.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tino.analytics.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tino.analytics.v1.AnalyticsService/DetectAnomalies',
            tino_dot_analytics_dot_v1_dot_analytics__pb2.DetectAnomaliesRequest.SerializeToString,
            tino_dot_analytics_dot_v1_dot_analytics__pb2.DetectAnomaliesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
