# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tino/data/v1/data.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'tino/data/v1/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17tino/data/v1/data.proto\x12\x0ctino.data.v1\"\xa0\x01\n\x11IngestDataRequest\x12\x16\n\x06source\x18\x01 \x01(\tR\x06source\x12\x1e\n\ninstrument\x18\x02 \x01(\tR\ninstrument\x12\x19\n\x08\x62\x61r_type\x18\x03 \x01(\tR\x07\x62\x61rType\x12\x1d\n\nstart_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n\x08\x65nd_date\x18\x05 \x01(\tR\x07\x65ndDate\"\xa8\x02\n\x12IngestDataResponse\x12>\n\x04type\x18\x01 \x01(\x0e\x32*.tino.data.v1.IngestDataResponse.EventTypeR\x04type\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12!\n\x0cprogress_pct\x18\x03 \x01(\x01R\x0bprogressPct\x12#\n\rrows_ingested\x18\x04 \x01(\x03R\x0crowsIngested\"p\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13\x45VENT_TYPE_PROGRESS\x10\x01\x12\x18\n\x14\x45VENT_TYPE_COMPLETED\x10\x02\x12\x14\n\x10\x45VENT_TYPE_ERROR\x10\x03\"\x14\n\x12ListCatalogRequest\"K\n\x13ListCatalogResponse\x12\x34\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.tino.data.v1.CatalogEntryR\x07\x65ntries\"\xa0\x01\n\x0c\x43\x61talogEntry\x12\x1e\n\ninstrument\x18\x01 \x01(\tR\ninstrument\x12\x19\n\x08\x62\x61r_type\x18\x02 \x01(\tR\x07\x62\x61rType\x12\x1d\n\nstart_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n\x08\x65nd_date\x18\x04 \x01(\tR\x07\x65ndDate\x12\x1b\n\trow_count\x18\x05 \x01(\x03R\x08rowCount\"Q\n\x14\x44\x65leteCatalogRequest\x12\x1e\n\ninstrument\x18\x01 \x01(\tR\ninstrument\x12\x19\n\x08\x62\x61r_type\x18\x02 \x01(\tR\x07\x62\x61rType\"1\n\x15\x44\x65leteCatalogResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success2\x8e\x02\n\x0b\x44\x61taService\x12Q\n\nIngestData\x12\x1f.tino.data.v1.IngestDataRequest\x1a .tino.data.v1.IngestDataResponse0\x01\x12R\n\x0bListCatalog\x12 .tino.data.v1.ListCatalogRequest\x1a!.tino.data.v1.ListCatalogResponse\x12X\n\rDeleteCatalog\x12\".tino.data.v1.DeleteCatalogRequest\x1a#.tino.data.v1.DeleteCatalogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tino.data.v1.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTDATAREQUEST']._serialized_start=42
  _globals['_INGESTDATAREQUEST']._serialized_end=202
  _globals['_INGESTDATARESPONSE']._serialized_start=205
  _globals['_INGESTDATARESPONSE']._serialized_end=501
  _globals['_INGESTDATARESPONSE_EVENTTYPE']._serialized_start=389
  _globals['_INGESTDATARESPONSE_EVENTTYPE']._serialized_end=501
  _globals['_LISTCATALOGREQUEST']._serialized_start=503
  _globals['_LISTCATALOGREQUEST']._serialized_end=523
  _globals['_LISTCATALOGRESPONSE']._serialized_start=525
  _globals['_LISTCATALOGRESPONSE']._serialized_end=600
  _globals['_CATALOGENTRY']._serialized_start=603
  _globals['_CATALOGENTRY']._serialized_end=763
  _globals['_DELETECATALOGREQUEST']._serialized_start=765
  _globals['_DELETECATALOGREQUEST']._serialized_end=846
  _globals['_DELETECATALOGRESPONSE']._serialized_start=848
  _globals['_DELETECATALOGRESPONSE']._serialized_end=897
  _globals['_DATASERVICE']._serialized_start=900
  _globals['_DATASERVICE']._serialized_end=1170
# @@protoc_insertion_point(module_scope)
